apiVersion: v1
kind: ConfigMap
metadata:
  name: pipeline-service-config
  namespace: kura
data:
  PIPELINE_SERVICE_PORT: "8084"
  ENV: "development"
  LOG_LEVEL: "info"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  REDIS_PASSWORD: ""
  REDIS_DB: "0"
  PIPELINE_CACHE_TTL: "24h"
